#!/bin/env ruby

=begin
Copyright 2017-2020 Marvin Johanning
This file is part of RubyTldr (rtldr).

Reeder is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Reeder is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Reeder.  If not, see <http://www.gnu.org/licenses/>.
=end

#For loading the tldr.rb file when the executable tldr file is located within the same folder as tldr.rb
#load "#{File.dirname(__FILE__)}/lib/bin/tldr.rb" 

#For loading the tldr.rb file when the executable tldr file is located in the .rtldr folder
load "~/.rtldr/lib/bin/tldr.rb"
