#!/bin/env ruby

#For loading the tldr.rb file when the executable tldr file is located within the same folder as tldr.rb
#load "#{File.dirname(__FILE__)}/lib/bin/tldr.rb" 

#For loading the tldr.rb file when the executable tldr file is located in the .rtldr folder
load "~/.rtldr/lib/bin/tldr.rb"
